const HTTP_BAD_REQUEST = 400;
const HTTP_CONFLICT = 409;
const HTTP_UNAUTHORIZED = 401;
const HTTP_CREATED = 201;
const HTTP_OK_STATUS = 200;

module.exports = {
  HTTP_BAD_REQUEST,
  HTTP_CONFLICT,
  HTTP_UNAUTHORIZED,
  HTTP_CREATED,
  HTTP_OK_STATUS,
};