const HTTP_OK_STATUS = 200;
const HTTP_UNPROCESSABLE_ENTITY = 422;
const HTTP_NOT_FOUND = 404;
const HTTP_CREATED = 201;
const HTTP_CONFLICT = 409;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_NO_CONTENT = 204;

module.exports = {
  HTTP_NOT_FOUND,
  HTTP_OK_STATUS,
  HTTP_UNPROCESSABLE_ENTITY,
  HTTP_CREATED,
  HTTP_CONFLICT,
  HTTP_BAD_REQUEST,
  HTTP_UNAUTHORIZED,
  HTTP_NO_CONTENT,
};